//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFarm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EFContext : DbContext
    {
        public EFContext()
            : base("name=EFContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Админ> Админ { get; set; }
        public virtual DbSet<АктСписанияКормов> АктСписанияКормов { get; set; }
        public virtual DbSet<Вид> Вид { get; set; }
        public virtual DbSet<Животные> Животные { get; set; }
        public virtual DbSet<Корм> Корм { get; set; }
    }
}
