//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFarm
{
    using System;
    using System.Collections.Generic;
    
    public partial class АктСписанияКормов
    {
        public int Код { get; set; }
        public Nullable<int> КодЖивотного { get; set; }
        public Nullable<int> КодКорма { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<int> Количество { get; set; }
    
        public virtual Животные Животные { get; set; }
        public virtual Корм Корм { get; set; }
    }
}
